name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.11' ]
        extras: [ 'base', 'aws', 'gcp', 'templates' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.extras }}" = "base" ]; then
            pip install -e .
          else
            pip install -e .[${{ matrix.extras }}]
          fi
          pip install pytest
      - name: Validate .env.example
        run: |
          python scripts/check_env_example.py
      - name: Run tests
        run: pytest -q
      - name: Add job summary (success)
        if: ${{ success() }}
        run: |
          PYTEST_VER=$(python - <<'PY'
          import pytest, sys
          print(getattr(pytest, '__version__', 'unknown'))
          PY
          )
          TOTAL_TESTS=$(pytest --collect-only -q 2>/dev/null | wc -l)
          {
            echo "### Test Job";
            echo "- Python: ${{ matrix.python-version }}";
            echo "- Extras: ${{ matrix.extras }}";
            echo "- Pytest: ${PYTEST_VER}";
            echo "- Collected tests: ${TOTAL_TESTS}";
            echo "- Status: success";
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Add job summary (failure)
        if: ${{ failure() }}
        run: |
          PYTEST_VER=$(python - <<'PY'
          import pytest, sys
          print(getattr(pytest, '__version__', 'unknown'))
          PY
          )
          TOTAL_TESTS=$(pytest --collect-only -q 2>/dev/null | wc -l)
          {
            echo "### Test Job";
            echo "- Python: ${{ matrix.python-version }}";
            echo "- Extras: ${{ matrix.extras }}";
            echo "- Pytest: ${PYTEST_VER}";
            echo "- Collected tests: ${TOTAL_TESTS}";
            echo "- Status: failure";
          } >> "$GITHUB_STEP_SUMMARY"
