name: Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps (ffmpeg optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg || true
      - name: Run smoke script
        run: |
          chmod +x scripts/smoke.sh
          ./scripts/smoke.sh
